const makes = [
  { id: 'Aston-Martin', text: 'Aston Martin' },
  { id: 'BMW', text: 'BMW' },
  { id: 'MINI', text: 'MINI' },
  { id: 'Rolls-Royce', text: 'Rolls-Royce' },
  { id: 'Mercedes-Benz', text: 'Mercedes-Benz' },
  { id: 'Smart', text: 'Smart' },
  { id: 'Alfa-Romeo', text: 'Alfa Romeo' },
  { id: 'Chrysler', text: 'Chrysler' },
  { id: 'Dodge', text: 'Dodge' },
  { id: 'FIAT', text: 'FIAT' },
  { id: 'Jeep', text: 'Jeep' },
  { id: 'Maserati', text: 'Maserati' },
  { id: 'Ram', text: 'Ram' },
  { id: 'Ferrari', text: 'Ferrari' },
  { id: 'Ford', text: 'Ford' },
  { id: 'Lincoln', text: 'Lincoln' },
  { id: 'Mercury', text: 'Mercury' },
  { id: 'Buick', text: 'Buick' },
  { id: 'Cadillac', text: 'Cadillac' },
  { id: 'Chevrolet', text: 'Chevrolet' },
  { id: 'GMC', text: 'GMC' },
  { id: 'Hummer', text: 'Hummer' },
  { id: 'Oldsmobile', text: 'Oldsmobile' },
  { id: 'Pontiac', text: 'Pontiac' },
  { id: 'Saturn', text: 'Saturn' },
  { id: 'Corvette', text: 'Corvette' },
  { id: 'Acura', text: 'Acura' },
  { id: 'Honda', text: 'Honda' },
  { id: 'Genesis', text: 'Genesis' },
  { id: 'Hyundai', text: 'Hyundai' },
  { id: 'KIA', text: 'KIA' },
  { id: 'Isuzu', text: 'Isuzu' },
  { id: 'Mazda', text: 'Mazda' },
  { id: 'McLaren', text: 'McLaren' },
  { id: 'Infiniti', text: 'Infiniti' },
  { id: 'Mitsubishi', text: 'Mitsubishi' },
  { id: 'Nissan', text: 'Nissan' },
  { id: 'Saab', text: 'Saab' },
  { id: 'Subaru', text: 'Subaru' },
  { id: 'Suzuki', text: 'Suzuki' },
  { id: 'Jaguar', text: 'Jaguar' },
  { id: 'Land-Rover', text: 'Land Rover' },
  { id: 'Tesla', text: 'Tesla' },
  { id: 'Lexus', text: 'Lexus' },
  { id: 'Scion', text: 'Scion' },
  { id: 'Toyota', text: 'Toyota' },
  { id: 'Audi', text: 'Audi' },
  { id: 'Bentley', text: 'Bentley' },
  { id: 'Bugatti', text: 'Bugatti' },
  { id: 'Lamborghini', text: 'Lamborghini' },
  { id: 'Porsche', text: 'Porsche' },
  { id: 'Volkswagen', text: 'Volkswagen' },
  { id: 'Lotus', text: 'Lotus' },
  { id: 'Volvo', text: 'Volvo' }
]

export default makes.sort((a, b) => a.text.localeCompare(b.text))
